### ISSUE TITLE
Mark sed exercise Srikanth-Aravamuthan

### ISSUE THREAD

**Issue by aravamu2** [aravamu2/notes#2]
@cecileane and @coraallencoleman

https://github.com/aravamu2/notes/blob/master/tableofSNPs.sh

- `tableofSNPs.sh` was developed under - Mac OS X El Capitan 10.11.6, and required macOS (via the use of `gsed`).
- run `tableofSNPs.sh` from the directory containing `tableofSNPs.sh` or copy and paste commands from file to Terminal
- creates csv files `task.csv` and `extra_task.csv`
- change every value in the "Minimum" column to eliminate
    - the commas inside the numbers and
    - the quotes around the numbers.
- permute the nucleotides back and recover the original data (changed all Ts to As and all As to Ts)
- alternative commands to perform tasks commented out and `echo` commands preceding `grep` and `sed` commands are included for readability when running script from Terminal

**Comment by cecileane** [comment]
great work!
