### ISSUE TITLE
Mark binomial in python of Srikanth-Aravamuthan

### ISSUE THREAD

**Issue by aravamu2** [aravamu2/notes#3]
@cecileane and @coraallencoleman

https://github.com/aravamu2/notes/commit/5b610ea349da1abf5ec705ed6f2a16d5acc649f3

- Use it in various ways from the shell:
```
./binomial.py --help
./binomial.py --test
./binomial.py -n 4 -k 2
./binomial.py -n 4 -k 2 --log
```
- Use it within python:
```
import binomial
help(binomial)
binomial.choose(4, 2)
binomial.choose(4, 2, True)
```
- Mac OS X El Capitan 10.11.6

**Comment by cecileane** [comment]
I like that your test includes cases where an error should be thrown :+1:
